### ISSUE TITLE
Unable to start from Commandline

### ISSUE THREAD

**Issue by dotIN** [opentable/wiremock-body-transformer#14]
Please help check the issue , it works with wiremock-body-transformer-1.0.4.jar but not latest jar

Java 1.8, Microsoft Windows 7 Enterprise 

**Command**
java -cp "wiremock-body-transformer-1.0.8.jar;wiremock-1.57-standalone.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --verbose --extensions com.ope
ntable.extension.BodyTransformer --port 9999
2016-05-11 16:35:45.385 Verbose logging enabled
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:98)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:62)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:110)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more

C:\Users\17raro\work\wiremock>dir

**Comment by KRoLer** [comment]
Hi @dotIN,

Please see this ticket: [link](https://github.com/opentable/wiremock-body-transformer/issues/9)

**Comment by dotIN** [comment]
Thanks @KRoLer that worked

**Comment by tranhungt** [comment]
Thanks @KRoLer
